### ISSUE TITLE
Building placement crash bug [not game breaking while playing]

### ISSUE THREAD

**Issue by KennyMcLean** [gyroid42/Petty-Kings#138]
**## Severity** - Quite severe, wont likely come up in gameplay if we can avoid it but can screw things up when testing

**## Area** - Village creation/ buildings

**## Description**
Upon placing a certain amount of buildings, the game and unity crash and have to be ended with task manager.
Could well be once you try to exceed the number of building spots though the game and unity did crash at a number of buildings lower than the current tile limit at the time.

**## Pre-requisite** - village spawned
**## reproduction steps** - keep placing buildings until the limit is reached
**## reproduction rate** - Every try so far

**## Comments** Not sure if hard limit or limit of how many tiles there are

**Comment by cc3397** [comment]
As previously mentioned it is to do with the amount of tiles in the game, the limit is 1 less than the amount of tiles in the game. Can try to add a condition where no building can be placed if it will cause crash but designers will still need to place tiles in the game to support the amount of buildings. I would recommend putting more tiles than are needed to increase the randomisation of the world for each play.

**Comment by cc3397** [comment]
Made it so if there are not enough tiles the building just wont spawn

**Comment by KennyMcLean** [comment]
cool cool thanks Ciaran
